package com.qterminals.report.engine;

import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

@Slf4j
public class ReportEngine {
    public ReportEngine() {
        log.info("Report Engine initiated (JAVA)");
    }

    public void GenerateReport() {
        log.info("Generating report");
        Map<String, Object> reportParams = new HashMap<>();
        reportParams.put("pReportTitle", "QTerminals");
        reportParams.put("pReportDescription", "Reporting engine to generate reports from Java/C#");
        reportParams.put("pMessage", "This report is generated by Java");

        JasperReportController jasperReportController = new JasperReportController();
        byte[] report = jasperReportController.getReportAsPDFFile(reportParams);

        String pdfPath = "C:/reports/report-java.pdf";
        try {
            Path path = Paths.get(pdfPath);
            OutputStream outputStream = Files.newOutputStream(path);
            outputStream.write(report);
            outputStream.close();
            log.info("Report has been generated at {}, ", pdfPath);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public byte[] GetGeneratedReport() {
        log.info("Generating report");
        Map<String, Object> reportParams = new HashMap<>();
        reportParams.put("pReportTitle", "QTerminals");
        reportParams.put("pReportDescription", "Reporting engine to generate reports from Java/C#");
        reportParams.put("pMessage", "This report is generated by Java");

        JasperReportController jasperReportController = new JasperReportController();
        byte[] report = jasperReportController.getReportAsPDFFile(reportParams);

        return report;
    }
}
